"""Command runner for the `eval` subcommand."""
from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path
import sys

from ..cli_ui import CLIHelpFormatter, branded_description, help_block, join_blocks
from ..core import CLIUsageError, DependencyError, make_default_module_output_dir, require_command
from .paper_pipeline import resolve_predictor_path, run_translation_validation

log = logging.getLogger("translation_validation")
_DEEPCIP_ENV = "MSTOCIRC2_DEEPCIP_PATH"
_DEEPCIP_PYTHON_ENV = "MSTOCIRC2_DEEPCIP_PYTHON"


def _resolve_output_dir(value: str | None) -> Path:
    if value and value.strip():
        output_dir = Path(value).expanduser()
        output_dir.mkdir(parents=True, exist_ok=True)
        return output_dir
    return make_default_module_output_dir("eval")


def _validate_eval_inputs(args: argparse.Namespace) -> tuple[str, str, str | None, str | None]:
    if args.circ_file_input:
        circ_dir = Path(args.circ_file_input)
        if not circ_dir.exists():
            raise CLIUsageError(f"Input result directory not found: '{circ_dir}'.")
        circ_seq = str(circ_dir / "circRNA_full_length.fasta")
        circ_orf = str(circ_dir / "circRNA_bsj_corf.fasta")
        circ_mapping = args.circ_mapping or str(circ_dir / "circRNA_ORF_mapping.tsv")
        circ_info = args.circ_info or str(circ_dir / "circ_info_omit.gff")
    else:
        if not args.circ_seq or not args.circ_orf:
            raise CLIUsageError(
                "Provide '--circ-file-input' or the pair '--circ-seq' and '--circ-orf'."
            )
        circ_seq = args.circ_seq
        circ_orf = args.circ_orf
        circ_mapping = args.circ_mapping
        circ_info = args.circ_info

    return circ_seq, circ_orf, circ_mapping, circ_info


def _configured_predictor_path(cli_value: str, env_name: str) -> str:
    return (cli_value or "").strip() or os.environ.get(env_name, "").strip()


def _configured_python_bin(cli_value: str, env_name: str) -> str:
    return (cli_value or "").strip() or os.environ.get(env_name, "").strip() or sys.executable


def _ensure_executable_on_path(executable: str) -> str:
    try:
        return require_command(executable)
    except DependencyError:
        python_bin_dir = Path(sys.executable).resolve().parent
        candidates = [python_bin_dir / executable]
        if os.name == "nt":
            candidates.append(python_bin_dir / f"{executable}.exe")
        for candidate in candidates:
            if candidate.exists():
                os.environ["PATH"] = str(python_bin_dir) + os.pathsep + os.environ.get("PATH", "")
                return require_command(executable)
        raise


def add_eval_subparser(subparsers: argparse._SubParsersAction) -> argparse.ArgumentParser:
    epilog = join_blocks(
        help_block(
            "Examples",
            [
                "  mstocirc2 eval -cs circ.fasta -co circ_orf.fasta -cm circ_mapping.tsv -ms peptide.tsv --deepcip-path /opt/DeepCIP --deepcip-python /opt/deepcip/bin/python -o out_eval",
            ],
        ),
    )
    eval_parser = subparsers.add_parser(
        "eval",
        help="MS translation evidence evaluation",
        formatter_class=CLIHelpFormatter,
        description=branded_description(
            "Evaluate peptide evidence against circRNA ORFs, generate circRNA translation support reports, "
            "and optionally integrate DeepCIP and DeepCircM6A predictor outputs.",
            "mstocirc2 eval -ms <PATH> -cp <FILE> [--circ-file-input <DIR> | --circ-seq <FILE> --circ-orf <FILE>] [options]",
        ),
        epilog=epilog,
    )
    eval_parser.set_defaults(runner=run_eval)
    eval_parser.add_argument(
        "-o",
        "--output-dir",
        dest="file_out",
        metavar="<DIR>",
        default=None,
        help=(
            "Directory for evaluation outputs and summary reports. If omitted, "
            "MStoCIRC2 creates 'MStoCIRC2_eval_YY-MM-DD.N' under the current "
            "working directory."
        ),
    )

    req = eval_parser.add_argument_group("Core inputs")
    req.add_argument(
        "-fi", "--circ-file-input",
        dest="circ_file_input",
        metavar="<DIR>",
        help=(
            "Path to the result directory generated by the ORF stage. If provided, "
            "MStoCIRC2 reads 'circRNA_full_length.fasta', 'circRNA_bsj_corf.fasta', "
            "and 'circRNA_ORF_mapping.tsv' from that directory."
        ),
    )
    req.add_argument(
        "-cs",
        "--circ-seq",
        dest="circ_seq",
        metavar="<FILE>",
        help="Path to the full-length mature circRNA FASTA file.",
    )
    req.add_argument(
        "-ci",
        "--circ-info",
        dest="circ_info",
        metavar="<FILE>",
        help="Path to the circRNA annotation table used for gene and strand annotation.",
    )
    req.add_argument(
        "-co",
        "--circ-orf",
        dest="circ_orf",
        metavar="<FILE>",
        help="Path to the predicted circRNA ORF FASTA exported by the ORF stage.",
    )
    req.add_argument(
        "-ms", "--ms-input", dest="path_ms_input", metavar="<PATH>", required=True,
        help="Mass-spectrometry result directory or peptide summary table. FragPipe-style tables must use circRNA ORF IDs matching the supplied ORF and mapping files.",
    )
    req.add_argument(
        "-cp",
        "--canonical-protein",
        dest="canonical_protein",
        metavar="<FILE>",
        required=True,
        help="Path to the canonical linear proteome FASTA used for background filtering.",
    )

    opt = eval_parser.add_argument_group("Optional settings")
    opt.add_argument(
        "-cm",
        "--circ-mapping",
        dest="circ_mapping",
        metavar="<FILE>",
        help="Path to the circRNA ORF mapping table.",
    )
    opt.add_argument(
        "--deepcip-path",
        dest="deepcip_path",
        metavar="<PATH>",
        default="",
        help=(
            "DeepCIP directory. Default: current environment lookup only. "
            f"You can also set '{_DEEPCIP_ENV}'."
        ),
    )
    opt.add_argument(
        "-dp", "--deepcip-python",
        dest="deepcip_python",
        metavar="<PATH>",
        default="",
        help=f"DeepCIP Python. Default: the current MStoCIRC2 Python or '{_DEEPCIP_PYTHON_ENV}'.",
    )

    return eval_parser


def run_eval(args: argparse.Namespace) -> int:
    circ_seq, circ_orf, circ_mapping, _circ_info = _validate_eval_inputs(args)
    out_dir = _resolve_output_dir(args.file_out)
    args.file_out = str(out_dir)
    script_dir = Path(__file__).resolve().parent
    deepcip_path = resolve_predictor_path(
        _configured_predictor_path(args.deepcip_path, _DEEPCIP_ENV),
        "DeepCIP.py",
        script_dir / "DeepCIP",
    )
    deepcircm6a_path = resolve_predictor_path(
        "",
        "predict.py",
        script_dir / "Deepcircm6a",
    )
    deepcip_python = _configured_python_bin(args.deepcip_python, _DEEPCIP_PYTHON_ENV)

    log.info("Evaluation stage started.")
    log.info("Output directory: %s", out_dir.resolve())
    if not deepcip_path:
        log.warning(
            "DeepCIP is unavailable. MS evidence evaluation will continue, but IRES-related "
            "translation-potential scoring will be incomplete."
        )
    if not deepcircm6a_path:
        log.warning(
            "DeepCircM6A is unavailable. MS evidence evaluation will continue, but m6A-related "
            "translation-potential scoring will be incomplete."
        )
    _ensure_executable_on_path("diamond")

    return run_translation_validation(
        circ_seq=circ_seq,
        circ_info_omit_file=_circ_info,
        circ_orf=circ_orf,
        circ_mapping=circ_mapping,
        path_ms_input=args.path_ms_input,
        file_input_protein=args.canonical_protein,
        file_out=str(out_dir),
        deepcip_path=deepcip_path,
        deepcip_python=deepcip_python,
        deepcircm6a_path=deepcircm6a_path,
    )
